# Generated by Django 4.2.23 on 2025-06-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_tender'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
